// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  26

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nftupgrade
    (
        init => init
        upgrade => upgrade
        initialize => initialize
        depositNft => deposit_nft
        retrieveNft => retrieve_nft
        upgradeNft => upgrade_nft
        increaseLevel => increase_level
        decreaseLevel => decrease_level
        getIsScPaused => is_sc_paused
        getAllowedAddresses => allowed_addresses
        getOwnerNftAddress => get_nft_owner_address
        getNftFromAddress => nft_from_address
        pauseSc => pause_sc
        resumeSc => resume_sc
        addAllowedAddresses => add_allowed_addresses
        getTags => get_tags
        getNftIdentifier => get_nft_identifier
        getNftIdentifierInvestors => get_nft_identifier_investors
        getNftAttributes => get_nft_attributes
        getNftUris => get_nft_uris
        getNftUriJson => get_nft_uri_json
        getNftAttributesLevelBeforeUpgrade => get_nft_attributes_level_before_upgrade
        getNftAttributesLevelAfterUpgrade => get_nft_attributes_level_after_upgrade
        getNftInfoBeforeUpgrade => get_nft_from_address_before
        getNftInfoAfterUpgrade => get_nft_from_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
