// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nftupgrade
    (
        init => init
        upgrade => upgrade
        initialize => initialize
        upgradeNft => upgrade_nft
        increaseLevel => increase_level
        decreaseLevel => decrease_level
        getNftAttributes => get_nft_attributes
        getNftAttributesLevelBeforeUpgrade => get_nft_attributes_level_before_upgrade
        getNftAttributesLevelAfterUpgrade => get_nft_attributes_level_after_upgrade
        getEmrNftIdentifier => emr_nft_identifier
        getIsScPaused => is_sc_paused
        pauseSc => pause_sc
        resumeSc => resume_sc
        setEmrNftIdentifier => set_emr_nft_identifier
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
