// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           37
// Async Callback (empty):               1
// Total number of exported functions:  40

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nftupgrade
    (
        init => init
        upgrade => upgrade
        initialize => initialize
        depositNft => deposit_nft
        retrieveNft => retrieve_nft
        claimNft => claim_nft
        upgradeNft => upgrade_nft
        increaseLevel => increase_level
        decreaseLevel => decrease_level
        getIsScPaused => is_sc_paused
        getAllowedAddresses => allowed_addresses
        getNftOwnerAddress => nft_owner_address
        getNftFromAddress => nft_from_address
        getNftRetrieveFromAddress => nft_retrieve_from_address
        getUserRetrieveEpoch => user_retrieve_epoch
        getUnbondingPeriod => unbonding_period
        getBlockedUsers => blocked_users
        pauseSc => pause_sc
        resumeSc => resume_sc
        setLevel => set_level
        blockUser => block_user
        unBlockUser => unblock_user
        addAllowedAddresses => add_allowed_addresses
        removeAllowedAddresses => remove_allowed_address
        setUnbondingPeriod => set_unbonding_period
        forceNftClaim => force_claim
        getNftIdentifier => get_nft_identifier
        getNftIdentifierInvestors => get_nft_identifier_investors
        getNftAttributes => get_nft_attributes
        getNftUriJson => get_nft_uri_json
        getNftAttributesLevelBeforeUpgrade => get_nft_attributes_level_before_upgrade
        getNftAttributesLevelAfterUpgrade => get_nft_attributes_level_after_upgrade
        getNftLevel => get_nft_level
        getNftInfoFromAddress => get_nft_info_from_address
        getNftInRetrieveByAddress => get_nft_in_retrieve_from_address
        getRemainingUnbondingTime => get_remaining_unbonding_time
        getUserInfo => ger_user_info
        getCustomNftInfo => get_custom_nft_info
        getAllNfts => get_all_nfts
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
